version: 2

jobs:
  build_jupyter_book:
    docker:
      - image: continuumio/miniconda
    environment:
      - OMP_NUM_THREADS: 1
      - MKL_NUM_THREADS: 2
      - OPENBLAS_NUM_THREADS: 2
      - MINICONDA_PATH: ~/miniconda
    steps:
      - checkout
      - run: chmod +x ./build_tools/circle/checkout_merge_commit.sh; ./build_tools/circle/checkout_merge_commit.sh
      - run:
          command: chmod +x ./build_tools/circle/build_jupyter_book.sh; ./build_tools/circle/build_jupyter_book.sh
          no_output_timeout: 30m
      - store_artifacts:
          path: CS328-Notes/_build/html
          destination: CS328-Notes

workflows:
  version: 2
  build_jupyter_book:
    jobs:
      # TODO add lint step
      # - lint
      - build_jupyter_book
          # requires:
          #   - lint
