name: Preview Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  preview-pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9.7]
    steps:
      - uses: actions/checkout@v2

      # Install Python and dependencies
      - name: Setup Python 3.9.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Build the book
      - name: Build the book
        run: jupyter-book build CS328-Notes

      # Archive jupyter book output
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: CS328-Notes/_build/html
          retention-days: 90
